### ISSUE TITLE
Redefinition of module 'SACodedTextField'

### ISSUE THREAD

**Issue by d33pak-s1ngh** [SandeepAggarwal/SACodedTextField#2]
Redefinition of module 'SACodedTextField' getting this error in module.modulemap file.
i am working with swift on xcode 9.3 and ios 11.
do you have a swift version of this?

**Comment by SandeepAggarwal** [comment]
@d33pak-s1ngh for a week I would be unable to fix this issue. Please feel free to fork it.
